{% set name = "rubicon-ml" %}
{% set version = "0.3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rubicon-ml-{{ version }}.tar.gz
  sha256: 3ae6752454c91f2aa35b0248cbe3febc685e121de98820d829693b4c42d60d67

build:
  number: 0
  noarch: python
  entry_points:
    - rubicon_ml=rubicon_ml.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - click <=8.1.2,>=7.1
    - dash <=2.3.1,>=2.0.0
    - dash-bootstrap-components <=1.1.0,>=1.0.0
    - dask <=2022.4.0,>=2.12.0
    - fsspec <=2022.3.0,>=2021.4.0
    - intake <=0.6.5,>=0.5.2
    - pandas <=1.4.2,>=1.0
    - prefect <=1.2.0,>=0.12.0
    - pyarrow <=7.0.0,>=0.18.0
    - python >=3.8
    - pyyaml <=6.0,>=5.4.0
    - s3fs <=2022.3.0,>=0.4

test:
  imports:
    - rubicon_ml
  commands:
    - rubicon_ml --help
  requires:
    - pip

about:
  home: https://github.com/capitalone/rubicon-ml
  doc_url: https://capitalone.github.io/rubicon-ml/
  summary: Client library and CLI for model development and governance
  license: Apache-2.0
  license_file: LICENSE
  description: |
    rubicon-ml is a data science tool that captures and stores model training and 
    execution information, like parameters and outcomes, in a repeatable and 
    searchable way. Rubicon's git integration associates these inputs and outputs 
    directly with the model code that produced them to ensure full auditability and 
    reproducibility for both developers and stakeholders alike. While experimenting, 
    the Rubicon dashboard makes it easy to explore, filter, visualize, and share 
    recorded work.

extra:
  recipe-maintainers:
    - joe-wolfe21
    - ryanSoley
    - mmccarty
    - dianelee217
