{% set name = "rubicon-ml" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rubicon-ml-{{ version }}.tar.gz
  sha256: edb2ac96a5faa63ccf39036bd375b601b38bbc5dda53e45ed979dbbcfa8c860e

build:
  number: 0
  noarch: python
  entry_points:
    - rubicon=rubicon.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=7.1
    - dask >=2.12.0
    - pandas >=1.0
    - fsspec >=2021.4.0
    - intake >=0.5.2
    - jupyter-dash
    - pyarrow >=0.18.0
    - python >=3.6
    - pyyaml >=5.4.0
    - s3fs >=0.4
    - prefect >=0.12.0
    - dash >=1.14.0
    - dash-bootstrap-components >=0.10.6

test:
  imports:
    - rubicon
  commands:
    - rubicon --help
  requires:
    - pip

about:
  home: https://github.com/capitalone/rubicon
  doc_url: https://capitalone.github.io/rubicon/
  summary: Client library and CLI for model development and governance
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Rubicon is a data science tool that captures and stores model training and 
    execution information, like parameters and outcomes, in a repeatable and 
    searchable way. Rubicon's git integration associates these inputs and outputs 
    directly with the model code that produced them to ensure full auditability and 
    reproducibility for both developers and stakeholders alike. While experimenting, 
    the Rubicon dashboard makes it easy to explore, filter, visualize, and share 
    recorded work.

extra:
  recipe-maintainers:
    - joe-wolfe21
    - ryanSoley
    - mmccarty
    - dianelee217
