{% set name = "rubicon-ml" %}
{% set version = "0.7.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rubicon-ml-{{ version }}.tar.gz
  sha256: 98849ec520fa3332452ec05d53161a141af648d55be89b9ebf047a06d648068d

build:
  number: 0
  noarch: python
  entry_points:
    - rubicon_ml=rubicon_ml.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - click <=8.1.7,>=7.1
    - dash <=2.16.1,>=2.0.0
    - dash-bootstrap-components <=1.6.0,>=1.0.0
    - fsspec <=2024.3.1,>=2021.4.0
    - intake <=2.0.5,>=0.5.2
    - jsonpath-ng <=1.6.1,>=1.5.3
    - numpy <=1.26.4,>=1.22.0
    - pandas <=2.2.2,>=1.0
    - prefect <=1.2.4,>=0.12.0
    - pyarrow <=16.0.0,>=14.0.1
    - python >=3.8
    - pyyaml <=6.0.1,>=5.4.0
    - s3fs <=2024.2.0,>=0.4
    - scikit-learn <=1.4.2,>=0.22.0

test:
  imports:
    - rubicon_ml
  commands:
    - rubicon_ml --help
  requires:
    - pip

about:
  home: https://github.com/capitalone/rubicon-ml
  doc_url: https://capitalone.github.io/rubicon-ml/
  summary: library and CLI for standardizing model development and governance
  license: Apache-2.0
  license_file: LICENSE
  description: |
    rubicon-ml is a machine learning solution designed to help standardize the model 
    development lifecycle. rubicon-ml can track, visualize and share experiments with 
    collaborators and reviewers as they develop, train and govern models designed 
    to solve complex business problems. It simplifies model governance, auditability 
    and reproducibility by tracking a wide range of model metadata.

extra:
  recipe-maintainers:
    - joe-wolfe21
    - ryanSoley
    - mmccarty
    - dianelee217
