{% set name = "rubicon-ml" %}
{% set version = "0.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rubicon-ml-{{ version }}.tar.gz
  sha256: 452d748ac16114cc9b1a4cd7705396f2b790c551a26d6bd61d356a28cbbff977

build:
  number: 0
  noarch: python
  entry_points:
    - rubicon_ml=rubicon_ml.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - click <=8.1.3,>=7.1
    - dash <=2.10.2,>=2.0.0
    - dash-bootstrap-components <=1.4.1,>=1.0.0
    - fsspec <=2023.5.0,>=2021.4.0
    - intake <=0.7.0,>=0.5.2
    - numpy <=1.24.3,>=1.22.0
    - pandas <=2.0.2,>=1.0
    - prefect <=1.2.4,>=0.12.0
    - pyarrow <=12.0.0,>=0.18.0
    - python >=3.8
    - pyyaml <=6.0,>=5.4.0
    - s3fs <=2023.5.0,>=0.4
    - scikit-learn <=1.2.2,>=0.22.0

test:
  imports:
    - rubicon_ml
  commands:
    - rubicon_ml --help
  requires:
    - pip

about:
  home: https://github.com/capitalone/rubicon-ml
  doc_url: https://capitalone.github.io/rubicon-ml/
  summary: library and CLI for standardizing model development and governance
  license: Apache-2.0
  license_file: LICENSE
  description: |
    rubicon-ml is a machine learning solution designed to help standardize the model 
    development lifecycle. rubicon-ml can track, visualize and share experiments with 
    collaborators and reviewers as they develop, train and govern models designed 
    to solve complex business problems. It simplifies model governance, auditability 
    and reproducibility by tracking a wide range of model metadata.

extra:
  recipe-maintainers:
    - joe-wolfe21
    - ryanSoley
    - mmccarty
    - dianelee217
