{% set name = "rubicon-ml" %}
{% set version = "0.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b1dc12d494019943610314df2160dfb52227060a12f20ab061783687686cc41c

build:
  number: 0
  noarch: python
  entry_points:
    - rubicon_ml=rubicon_ml.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click <=8.2.1,>=7.1
    - dash <=2.18.2,>=2.0.0
    - dash-bootstrap-components <=1.7.1,>=1.0.0
    - fsspec <=2025.7.0,>=2021.4.0
    - intake <=2.0.7,>=0.5.2
    - jsonpath-ng <=1.7.0,>=1.5.3
    - numpy <=2.3.1,>=1.22.0
    - pandas <=2.3.1,>=1.0
    - pyarrow <=21.0.0,>=14.0.1
    - python >={{ python_min }}
    - pyyaml <=6.0.2,>=5.4.0
    - s3fs <=2025.7.0,>=0.4
    - scikit-learn <=1.7.1,>=0.22.0

test:
  imports:
    - rubicon_ml
  commands:
    - rubicon_ml --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/capitalone/rubicon-ml
  doc_url: https://capitalone.github.io/rubicon-ml/
  summary: library and CLI for standardizing model development and governance
  license: Apache-2.0
  license_file: LICENSE
  description: |
    rubicon-ml is a machine learning solution designed to help standardize the model 
    development lifecycle. rubicon-ml can track, visualize and share experiments with 
    collaborators and reviewers as they develop, train and govern models designed 
    to solve complex business problems. It simplifies model governance, auditability 
    and reproducibility by tracking a wide range of model metadata.

extra:
  recipe-maintainers:
    - joe-wolfe21
    - ryanSoley
    - mmccarty
    - dianelee217
