{% set name = "rubicon-ml" %}
{% set version = "0.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rubicon-ml-{{ version }}.tar.gz
  sha256: 23e61f2f7bc5ef0a4e965de13736ff1ac8748d9a3471e08f29623e6d26328bd2

build:
  number: 0
  noarch: python
  entry_points:
    - rubicon_ml=rubicon_ml.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=7.1
    - dask >=2.12.0
    - pandas >=1.0
    - fsspec >=2021.4.0
    - intake >=0.5.2
    - jupyter-dash
    - pyarrow >=0.18.0
    - python >=3.6
    - pyyaml >=5.4.0
    - s3fs >=0.4
    - prefect >=0.12.0
    - dash >=1.14.0
    - dash-bootstrap-components >=0.10.6

test:
  imports:
    - rubicon_ml
  commands:
    - rubicon_ml --help
  requires:
    - pip

about:
  home: https://github.com/capitalone/rubicon-ml
  doc_url: https://capitalone.github.io/rubicon-ml/
  summary: Client library and CLI for model development and governance
  license: Apache-2.0
  license_file: LICENSE
  description: |
    rubicon-ml is a data science tool that captures and stores model training and 
    execution information, like parameters and outcomes, in a repeatable and 
    searchable way. Rubicon's git integration associates these inputs and outputs 
    directly with the model code that produced them to ensure full auditability and 
    reproducibility for both developers and stakeholders alike. While experimenting, 
    the Rubicon dashboard makes it easy to explore, filter, visualize, and share 
    recorded work.

extra:
  recipe-maintainers:
    - joe-wolfe21
    - ryanSoley
    - mmccarty
    - dianelee217
